-- V5__add_rbac_auth.sql
-- Description: Add role-based authentication and authorization schema without breaking existing tables

BEGIN;

-- 1. Create Users Table (Authentication Core)
CREATE TABLE public.users (
                              id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                              email character varying(255) NOT NULL,
                              password_hash character varying(255) NOT NULL,
                              is_active boolean DEFAULT true NOT NULL,
                              created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
                              updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
                              CONSTRAINT users_pkey PRIMARY KEY (id),
                              CONSTRAINT users_email_key UNIQUE (email)
);

-- 2. Create Roles Table
CREATE TABLE public.roles (
                              id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                              name character varying(50) NOT NULL,
                              description text,
                              created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
                              CONSTRAINT roles_pkey PRIMARY KEY (id),
                              CONSTRAINT roles_name_key UNIQUE (name)
);

-- 3. Create Permissions Table (Fine-grained authorization)
CREATE TABLE public.permissions (
                                    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                    name character varying(100) NOT NULL,
                                    description text,
                                    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                    CONSTRAINT permissions_pkey PRIMARY KEY (id),
                                    CONSTRAINT permissions_name_key UNIQUE (name)
);

-- 4. Create User-Roles Junction Table
CREATE TABLE public.user_roles (
                                   user_id integer NOT NULL,
                                   role_id integer NOT NULL,
                                   assigned_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                   CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id),
                                   CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id)
                                       REFERENCES public.users(id) ON DELETE CASCADE,
                                   CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id)
                                       REFERENCES public.roles(id) ON DELETE CASCADE
);

-- 5. Create Role-Permissions Junction Table
CREATE TABLE public.role_permissions (
                                         role_id integer NOT NULL,
                                         permission_id integer NOT NULL,
                                         CONSTRAINT role_permissions_pkey PRIMARY KEY (role_id, permission_id),
                                         CONSTRAINT fk_role_permissions_role FOREIGN KEY (role_id)
                                             REFERENCES public.roles(id) ON DELETE CASCADE,
                                         CONSTRAINT fk_role_permissions_permission FOREIGN KEY (permission_id)
                                             REFERENCES public.permissions(id) ON DELETE CASCADE
);

-- 6. Connect Existing Customers Table to Authentication non-destructively
ALTER TABLE public.customers
    ADD COLUMN user_id integer UNIQUE,
    ADD CONSTRAINT fk_customers_user FOREIGN KEY (user_id)
        REFERENCES public.users(id) ON DELETE SET NULL;

-- 7. Add Performance Indexes
CREATE INDEX idx_users_email ON public.users USING btree (email);
CREATE INDEX idx_user_roles_user ON public.user_roles USING btree (user_id);
CREATE INDEX idx_user_roles_role ON public.user_roles USING btree (role_id);
CREATE INDEX idx_role_permissions_role ON public.role_permissions USING btree (role_id);
CREATE INDEX idx_customers_user_id ON public.customers USING btree (user_id);

-- 8. Seed Default Access Roles
INSERT INTO public.roles (name, description) VALUES
                                                 ('ROLE_ADMIN', 'Full administrative access to manage marketplace data and users'),
                                                 ('ROLE_STAFF', 'Internal operational access for managing inventory, locations, and orders'),
                                                 ('ROLE_CUSTOMER', 'Standard shopper access to manage personal profile, orders, and reviews');

COMMIT;